"""Functional tests: every dashboard page renders without exceptions.

Uses Streamlit's official AppTest runner (replaces the old mock_streamlit
scratch tool). Requires `streamlit` and the processed datasets
(data/processed/*.csv, regenerated by notebooks 02 and 04).
"""

import glob
from pathlib import Path

import pytest

pytest.importorskip("streamlit")
from streamlit.testing.v1 import AppTest  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent.parent
PAGES = [str(ROOT / "dashboard" / "app.py")] + sorted(
    glob.glob(str(ROOT / "dashboard" / "pages" / "*.py"))
)


@pytest.mark.parametrize("page", PAGES, ids=lambda p: Path(p).name)
def test_page_renders_without_exception(page):
    at = AppTest.from_file(page, default_timeout=90).run()
    assert not at.exception, [e.value for e in at.exception]


def test_all_expected_pages_present():
    assert len(PAGES) == 9  # app.py + 8 pages (PRD UI-NAV-001)
